# Generated by Django 5.1 on 2024-09-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='france_immobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transaction', models.DateTimeField(blank=True, null=True)),
                ('id_transaction', models.FloatField(blank=True, null=True)),
                ('ville', models.TextField(blank=True, null=True)),
                ('departement', models.FloatField(blank=True, null=True)),
                ('prix', models.FloatField(blank=True, null=True)),
                ('pps', models.FloatField(blank=True, null=True)),
                ('type_batiment', models.TextField(blank=True, null=True)),
                ('interest', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hist',
                'managed': False,
            },
        ),
    ]
